[build]
  command = "pip install -r requirements.txt && python app.py"
  publish = "/"

[[plugins]]
  package = "netlify-plugin-python"
  [plugins.inputs]
  pythonVersion = "3.10"
  pipCommand = "install -r requirements.txt"
